repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.50.0
  hooks:
    - id: terraform_validate
      files: (\.tf|\.tfvars)$
      exclude: \.terraform\/.*$
  
    - id: terraform_fmt
      files: (\.tf|\.tfvars)$
      exclude: \.terraform\/.*$

    - id: terraform_tfsec
      files: (\.tf|\.tfvars)$
      exclude: \.terraform\/.*$
        
    - id: terraform_docs
    - id: terraform_docs_replace